//SOUND RANDOM ☘️
exports.sound1 = ("https://pomf2.lain.la/f/m92ulq79.mp3")
exports.sound2 = ("https://pomf2.lain.la/f/9uoobkk.mp3")
exports.sound3 = ("https://pomf2.lain.la/f/f0s1bmnk.mp3")
exports.sound4 = ("https://pomf2.lain.la/f/858jpl8o.mp3")
exports.sound5 = ("https://pomf2.lain.la/f/4n0cq92s.mp3")
exports.sound6 = ("https://pomf2.lain.la/f/kg5df2ee.mp3")
exports.sound7 = ("https://pomf2.lain.la/f/w3bk4pg.mp3")
exports.sound8 = ("https://pomf2.lain.la/f/2cflrl5e.mp3")
exports.sound9 = ("https://pomf2.lain.la/f/pf8by2q2.mp3")
exports.sound10 = ("https://pomf2.lain.la/f/yfs0klo6.mp3")
exports.sound11= ("https://pomf2.lain.la/f/g0vmjes.mp3")
exports.sound12 = ("https://pomf2.lain.la/f/t2s93pi.mp3")
exports.sound13 = ("https://pomf2.lain.la/f/kkw4uca1.mp3")
exports.sound14 = ("https://pomf2.lain.la/f/t6na12o3.mp3")
exports.sound15 = ("https://pomf2.lain.la/f/k21quaqu.mp3")
exports.sound16 = ("https://pomf2.lain.la/f/h93m7zb.mp3")
exports.sound17 = ("https://pomf2.lain.la/f/mwqdmwkt.mp3")
exports.sound18 = ("https://pomf2.lain.la/f/er1nj4en.mp3")
exports.sound19 = ("https://pomf2.lain.la/f/1b8zxmmr.mp3")
exports.sound20 = ("https://pomf2.lain.la/f/ldrxzq59.mp3")
exports.sound21 = ("https://pomf2.lain.la/f/tgnke3n.mp3")
exports.sound22 = ("https://pomf2.lain.la/f/mwqdmwkt.mp3")
exports.sound23 = ("https://pomf2.lain.la/f/ukbma1xq.mp3")

//SOUND VNBOT ☘️
exports.vnWalikumsalam = ("https://pomf2.lain.la/f/7ixvc40h.mp3")
exports.vnBang = ("https://pomf2.lain.la/f/a2cmxdzl.mp3")
